// Code generated by hertz generator.

package auth

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	authlogic "github.com/xinjiyuan97/labor-clients/biz/logic/auth"
	auth "github.com/xinjiyuan97/labor-clients/biz/model/auth"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

// ChangePassword .
// @router /api/v1/auth/change-password [POST]
func ChangePassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.ChangePasswordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 从上下文获取用户ID
	userID, exists := middleware.GetUserIDFromContext(c)
	if !exists {
		c.String(consts.StatusUnauthorized, "未登录")
		return
	}

	resp, err := authlogic.ChangePasswordLogic(int64(userID), &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
