// Code generated by hertz generator.

package auth

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	authlogic "github.com/xinjiyuan97/labor-clients/biz/logic/auth"
	auth "github.com/xinjiyuan97/labor-clients/biz/model/auth"
)

// Login .
// @router /api/v1/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := authlogic.LoginLogic(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
