// Code generated by hertz generator.

package schedule

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _schedulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getschedulelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletescheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _schedule_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getscheduledetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateschedulestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatescheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettodayscheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createscheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}
