// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoritesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmyfavoritesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unfavoritejobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoritejobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _incomeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getincomeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getincomedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getperformanceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadcertMw() []app.HandlerFunc {
	// your code...
	return nil
}
