// Code generated by hertz generator.

package message

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmessagelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchmarkreadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _message_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmessagedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _markmessagereadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getunreadcountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}
