// Code generated by hertz generator.

package job

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbrandlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjobcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _jobsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjoblistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjobdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecommendjobsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchjobsMw() []app.HandlerFunc {
	// your code...
	return nil
}
