// Code generated by hertz generator.

package review

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	reviewlogic "github.com/xinjiyuan97/labor-clients/biz/logic/review"
	review "github.com/xinjiyuan97/labor-clients/biz/model/review"
)

// GetReviewDetail .
// @router /api/v1/reviews/:review_id [GET]
func GetReviewDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req review.GetReviewDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := reviewlogic.GetReviewDetailLogic(&req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
