// Code generated by hertz generator.

package review

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	reviewlogic "github.com/xinjiyuan97/labor-clients/biz/logic/review"
	review "github.com/xinjiyuan97/labor-clients/biz/model/review"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

// GetGivenReviews .
// @router /api/v1/reviews/given [GET]
func GetGivenReviews(ctx context.Context, c *app.RequestContext) {
	var err error
	var req review.GetGivenReviewsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID, exists := middleware.GetUserIDFromContext(c)
	if !exists {
		c.String(consts.StatusUnauthorized, "未登录")
		return
	}

	resp, err := reviewlogic.GetGivenReviewsLogic(int64(userID), &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
