// Code generated by hertz generator.

package review

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	review "github.com/xinjiyuan97/labor-clients/biz/model/review"
)

// GetGivenReviews .
// @router /api/v1/reviews/given [GET]
func GetGivenReviews(ctx context.Context, c *app.RequestContext) {
	var err error
	var req review.GetGivenReviewsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(review.GetGivenReviewsResp)

	c.JSON(consts.StatusOK, resp)
}
