// Code generated by hertz generator.

package review

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	review "github.com/xinjiyuan97/labor-clients/biz/model/review"
)

// UpdateReview .
// @router /api/v1/reviews/:review_id [PUT]
func UpdateReview(ctx context.Context, c *app.RequestContext) {
	var err error
	var req review.UpdateReviewReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(review.UpdateReviewResp)

	c.JSON(consts.StatusOK, resp)
}
