// Code generated by hertz generator.

package community

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _communityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcoursesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _post_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unlikepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpostdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpostMw() []app.HandlerFunc {
	// your code...
	return nil
}
