// Code generated by hertz generator.

package payment

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	payment "github.com/xinjiyuan97/labor-clients/biz/model/payment"
)

// GetWithdrawRecords .
// @router /api/v1/payments/withdraw-records [GET]
func GetWithdrawRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.GetWithdrawRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(payment.GetWithdrawRecordsResp)

	c.JSON(consts.StatusOK, resp)
}
