// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// AssignStoreAdmin .
// @router /api/v1/admin/stores/:store_id/admins [POST]
func AssignStoreAdmin(ctx context.Context, c *app.RequestContext) {
	// TODO: 该功能可以通过CreateUser接口实现，指定role为store_admin和store_id
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    0,
		"message": "请使用CreateUser接口创建门店管理员",
	})
}
