// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	adminlogic "github.com/xinjiyuan97/labor-clients/biz/logic/admin"
	admin "github.com/xinjiyuan97/labor-clients/biz/model/admin"
	"github.com/xinjiyuan97/labor-clients/errno"
)

// CreateBrandAdmin .
// @router /api/v1/admin/brands/admins [POST]
func CreateBrandAdmin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreateBrandAdminReq
	var resp admin.CreateBrandAdminResp
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用业务逻辑
	roleID, err := adminlogic.CreateBrandAdmin(ctx, req.Phone, req.RealName, req.BrandID, req.RoleType)
	if err != nil {
		resp.Base = errno.GetBaseResp(err)
		c.JSON(int(resp.Base.Code), resp)
		return
	}

	resp.RoleID = roleID
	c.JSON(consts.StatusOK, resp)
}
