// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	adminlogic "github.com/xinjiyuan97/labor-clients/biz/logic/admin"
	admin "github.com/xinjiyuan97/labor-clients/biz/model/admin"
)

// CreateAdmin .
// @router /api/v1/admin/admins [POST]
func CreateAdmin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreateAdminReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := adminlogic.CreateAdminLogic(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
