// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	adminlogic "github.com/xinjiyuan97/labor-clients/biz/logic/admin"
	admin "github.com/xinjiyuan97/labor-clients/biz/model/admin"
	"github.com/xinjiyuan97/labor-clients/errno"
)

// CreateBrand .
// @router /api/v1/admin/brands [POST]
func CreateBrand(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CreateBrandReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用业务逻辑
	resp, err := adminlogic.CreateBrandLogic(ctx, &req)
	if err != nil {
		resp.Base = errno.GetBaseResp(err)
		c.JSON(200, resp)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
