// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	adminlogic "github.com/xinjiyuan97/labor-clients/biz/logic/admin"
	admin "github.com/xinjiyuan97/labor-clients/biz/model/admin"
)

// GetStoreDetail .
// @router /api/v1/admin/stores/:store_id [GET]
func GetStoreDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetStoreDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用业务逻辑
	resp, err := adminlogic.GetStoreDetail(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
