// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	admin "github.com/xinjiyuan97/labor-clients/biz/model/admin"
)

// GetBrandStatistics .
// @router /api/v1/admin/statistics/brands [GET]
func GetBrandStatistics(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetBrandStatisticsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.GetBrandStatisticsResp)

	c.JSON(consts.StatusOK, resp)
}
