// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	adminlogic "github.com/xinjiyuan97/labor-clients/biz/logic/admin"
	admin "github.com/xinjiyuan97/labor-clients/biz/model/admin"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

// GetAdminInfo .
// @router /api/v1/admin/info [GET]
func GetAdminInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetAdminInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	role, exists := middleware.GetUserRoleFromContext(c)
	if !exists {
		c.String(consts.StatusUnauthorized, "未登录")
		return
	}

	resp := &admin.GetAdminInfoResp{}

	baseResp := adminlogic.CheckAdminRole(ctx, role)
	if baseResp.Code != 200 {
		resp.Base = baseResp
		c.JSON(consts.StatusForbidden, resp)
		return
	}

	// 调用业务逻辑
	resp, err = adminlogic.GetAdminInfo(ctx, c, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	menus, err := adminlogic.GetMenus(ctx, role)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.Menus = menus

	c.JSON(consts.StatusOK, resp)
}
