// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// RemoveStoreAdmin .
// @router /api/v1/admin/stores/:store_id/admins [DELETE]
func RemoveStoreAdmin(ctx context.Context, c *app.RequestContext) {
	// TODO: 该功能可以通过UpdateUser接口实现，修改用户的store_id或删除用户
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    0,
		"message": "请使用UpdateUser接口修改门店管理员",
	})
}
