// Code generated by hertz generator.

package review

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatereviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviews0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgivenreviewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreceivedreviewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreviewdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}
