# 生产环境配置文件

# Web服务器配置
server:
  host: "0.0.0.0"           # 服务器监听地址
  port: 8080                 # 服务器端口
  read_timeout: 60           # 读取超时时间(秒)
  write_timeout: 60          # 写入超时时间(秒)
  idle_timeout: 300          # 空闲超时时间(秒)
  mode: "release"            # 运行模式: debug, release, test

# 数据库配置
database:
  driver: "mysql"            # 数据库驱动
  host: "your-db-host"       # 数据库主机地址
  port: 3306                 # 数据库端口
  username: "your_username"  # 数据库用户名
  password: "your_password"  # 数据库密码
  database: "labor_clients"  # 数据库名
  charset: "utf8mb4"         # 字符集
  max_open_conns: 200        # 最大打开连接数
  max_idle_conns: 20         # 最大空闲连接数
  conn_max_lifetime: 3600    # 连接最大生命周期(秒)
  log_level: "error"         # 日志级别: silent, error, warn, info

# Redis配置
redis:
  host: "your-redis-host"    # Redis主机地址
  port: 6379                 # Redis端口
  password: "your_redis_password"  # Redis密码
  database: 0                # Redis数据库编号
  pool_size: 200             # 连接池大小
  min_idle_conns: 20         # 最小空闲连接数
  dial_timeout: 5            # 连接超时时间(秒)
  read_timeout: 3            # 读取超时时间(秒)
  write_timeout: 3           # 写入超时时间(秒)

# 对象存储配置
oss:
  provider: "aliyun"         # 存储提供商: aliyun, tencent, aws, local
  access_key: "your_access_key"    # 访问密钥
  secret_key: "your_secret_key"    # 秘密密钥
  region: "cn-hangzhou"      # 区域
  bucket: "your-bucket"      # 存储桶名称
  endpoint: "oss-cn-hangzhou.aliyuncs.com"  # 端点地址
  base_url: "https://your-bucket.oss-cn-hangzhou.aliyuncs.com/"  # 基础URL
  upload_path: "/app/uploads/"  # 本地上传路径
  max_file_size: 52428800    # 最大文件大小(50MB)
  allowed_exts:              # 允许的文件扩展名
    - "jpg"
    - "jpeg"
    - "png"
    - "gif"
    - "pdf"
    - "doc"
    - "docx"
    - "xls"
    - "xlsx"

# 日志配置
log:
  level: "warn"              # 日志级别: debug, info, warn, error, fatal, panic
  format: "json"             # 日志格式: json, text
  output: "file"             # 输出方式: file, stdout, both
  file_path: "/app/logs/app.log"  # 日志文件路径
  max_size: 200              # 单个日志文件最大大小(MB)
  max_backups: 30            # 保留的日志文件数量
  max_age: 90                # 日志文件保留天数
  compress: true             # 是否压缩旧日志文件

# 鉴权配置
auth:
  jwt_secret: "your-super-secret-jwt-key-for-production-environment"  # JWT密钥(生产环境请修改)
  jwt_expire: 24             # JWT过期时间(小时)
  refresh_expire: 7          # 刷新令牌过期时间(天)
  issuer: "labor-clients"    # JWT签发者
  audience: "labor-clients"  # JWT受众
  algorithm: "HS256"         # 签名算法

# 雪花算法配置
snowflake:
  node_id: 1                 # 节点ID(0-1023)
