// Code generated by hertz generator.

package payment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpaymentrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpaymentdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applywithdrawMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getwithdrawrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}
