// Code generated by hertz generator.

package message

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	message "github.com/xinjiyuan97/labor-clients/biz/model/message"
)

// BatchMarkRead .
// @router /api/v1/messages/batch-read [PUT]
func BatchMarkRead(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.BatchMarkReadReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.BatchMarkReadResp)

	c.JSON(consts.StatusOK, resp)
}
