// Code generated by hertz generator.

package message

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	message "github.com/xinjiyuan97/labor-clients/biz/model/message"
)

// GetMessageList .
// @router /api/v1/messages [GET]
func GetMessageList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.GetMessageListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(message.GetMessageListResp)

	c.JSON(consts.StatusOK, resp)
}
