// Code generated by hertz generator.

package message

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	messagelogic "github.com/xinjiyuan97/labor-clients/biz/logic/message"
	message "github.com/xinjiyuan97/labor-clients/biz/model/message"
)

// SendMessage .
// @router /api/v1/messages [POST]
func SendMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req message.SendMessageReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := messagelogic.SendMessageLogic(&req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
