// Code generated by hertz generator.

package job_application

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _job_applicationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getapplicationlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _application_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getapplicationdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelapplicationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confirmapplicationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmyapplicationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyjobMw() []app.HandlerFunc {
	// your code...
	return nil
}
