// Code generated by hertz generator.

package upload

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadcertfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}
