// Code generated by hertz generator.

package job

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	job "github.com/xinjiyuan97/labor-clients/biz/model/job"
)

// GetJobDetail .
// @router /api/v1/jobs/:job_id [GET]
func GetJobDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req job.GetJobDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(job.GetJobDetailResp)

	c.JSON(consts.StatusOK, resp)
}
