// Code generated by hertz generator.

package community

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	communitylogic "github.com/xinjiyuan97/labor-clients/biz/logic/community"
	community "github.com/xinjiyuan97/labor-clients/biz/model/community"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

// CreatePost .
// @router /api/v1/community/posts [POST]
func CreatePost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req community.CreatePostReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID, exists := middleware.GetUserIDFromContext(c)
	if !exists {
		c.String(consts.StatusUnauthorized, "未登录")
		return
	}

	resp, err := communitylogic.CreatePostLogic(ctx, userID, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
