// Code generated by hertz generator.

package community

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	community "github.com/xinjiyuan97/labor-clients/biz/model/community"
)

// GetCommentList .
// @router /api/v1/community/posts/:post_id/comments [GET]
func GetCommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req community.GetCommentListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(community.GetCommentListResp)

	c.JSON(consts.StatusOK, resp)
}
