// Code generated by hertz generator.

package admin

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWTAuth(),
		middleware.RequireAdminRole(),
	}
}

func _getadminlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _brandsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbrandlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchimportbrandsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _brand_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbranddetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewbrandMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebrandMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbrandMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _jobsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjoblistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _job_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewjobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmessagetemplateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoticelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendsystemnoticeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsystemconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesystemconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _financeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getincomestatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settlementsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsettlementlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settlement_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _processsettlementMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbrandstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjobstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}
