// Code generated by hertz generator.

package admin

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/xinjiyuan97/labor-clients/constants"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWTAuth(),
	}
}

func _getadminlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createadminMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.RequireAnyRole(constants.RoleAdmin),
	}
}

func _brandsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbrandlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchimportbrandsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _brand_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbranddetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewbrandMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebrandMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbrandMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.RequireAdminRole(),
	}
}

func _jobsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjoblistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _job_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewjobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmessagetemplateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoticelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendsystemnoticeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsystemconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesystemconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _financeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getincomestatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settlementsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsettlementlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settlement_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _processsettlementMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbrandstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjobstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserstatisticsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admin_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetadminpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admin_id0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _disableadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _enableadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _storesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstorelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _store_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstoredetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createstoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatestoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletestoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assignstoreadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removestoreadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmenusMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.RequireAnyRole(constants.RoleAdmin, constants.RoleEmployer),
	}
}

func _createbrandadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbrandadminsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createstoreadminMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.RequireAnyRole(constants.RoleAdmin, constants.RoleEmployer),
	}
}

func _brand_adminsMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.RequireAnyRole(constants.RoleAdmin, constants.RoleEmployer),
	}
}

func _role_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebrandadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebrandadminstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getadmininfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
