// Code generated by hertz generator.

package job_application

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	job_application "github.com/xinjiyuan97/labor-clients/biz/model/job_application"
)

// GetApplicationList .
// @router /api/v1/job-applications [GET]
func GetApplicationList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req job_application.GetApplicationListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(job_application.GetApplicationListResp)

	c.JSON(consts.StatusOK, resp)
}
