// Code generated by hertz generator.

package system

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsystemconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _noticesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoticelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoticedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getversionMw() []app.HandlerFunc {
	// your code...
	return nil
}
