// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	userlogic "github.com/xinjiyuan97/labor-clients/biz/logic/user"
	user "github.com/xinjiyuan97/labor-clients/biz/model/user"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

// GetIncomeDetail .
// @router /api/v1/user/income/detail [GET]
func GetIncomeDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetIncomeDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 从上下文中获取用户ID
	userID, exists := middleware.GetUserIDFromContext(c)
	if !exists {
		c.String(consts.StatusUnauthorized, "未登录")
		return
	}

	resp, err := userlogic.GetIncomeDetailLogic(&req, userID)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
