// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	userlogic "github.com/xinjiyuan97/labor-clients/biz/logic/user"
	user "github.com/xinjiyuan97/labor-clients/biz/model/user"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

// UnfavoriteJob .
// @router /api/v1/user/favorites/:job_id [DELETE]
func UnfavoriteJob(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UnfavoriteJobReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 从上下文中获取用户ID
	userID, exists := middleware.GetUserIDFromContext(c)
	if !exists {
		c.String(consts.StatusUnauthorized, "未登录")
		return
	}

	resp, err := userlogic.UnfavoriteJobLogic(ctx, &req, userID)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
