// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "github.com/xinjiyuan97/labor-clients/biz/model/user"
)

// UnfavoriteJob .
// @router /api/v1/user/favorites/:job_id [DELETE]
func UnfavoriteJob(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UnfavoriteJobReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UnfavoriteJobResp)

	c.JSON(consts.StatusOK, resp)
}
