// Code generated by hertz generator.

package auth

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserprofileMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}
