// Code generated by hertz generator.

package schedule

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	schedulelogic "github.com/xinjiyuan97/labor-clients/biz/logic/schedule"
	schedule "github.com/xinjiyuan97/labor-clients/biz/model/schedule"
)

// CreateSchedule .
// @router /api/v1/schedules [POST]
func CreateSchedule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req schedule.CreateScheduleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := schedulelogic.CreateScheduleLogic(&req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
