// Code generated by hertz generator.

package schedule

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	schedule "github.com/xinjiyuan97/labor-clients/biz/model/schedule"
)

// GetScheduleDetail .
// @router /api/v1/schedules/:schedule_id [GET]
func GetScheduleDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req schedule.GetScheduleDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(schedule.GetScheduleDetailResp)

	c.JSON(consts.StatusOK, resp)
}
