// Code generated by hertz generator.

package upload

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	uploadlogic "github.com/xinjiyuan97/labor-clients/biz/logic/upload"
	upload "github.com/xinjiyuan97/labor-clients/biz/model/upload"
	"github.com/xinjiyuan97/labor-clients/config"
)

// GetSignedURL .
// @router /api/v1/upload/signed-url [GET]
func GetSignedURL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.GetSignedURLReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用业务逻辑
	resp, err := uploadlogic.GetSignedURLLogic(req.FileURL, req.ExpireSeconds, &config.GetGlobalConfig().OSS)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
