// Code generated by hertz generator.

package upload

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	upload "github.com/xinjiyuan97/labor-clients/biz/model/upload"
)

// UploadCertFile .
// @router /api/v1/upload/cert [POST]
func UploadCertFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.UploadCertFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(upload.UploadCertFileResp)

	c.JSON(consts.StatusOK, resp)
}
