// Code generated by hertz generator.

package upload

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	upload "github.com/xinjiyuan97/labor-clients/biz/model/upload"
)

// UploadFile .
// @router /api/v1/upload/file [POST]
func UploadFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.UploadFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(upload.UploadFileResp)

	c.JSON(consts.StatusOK, resp)
}
