// Code generated by hertz generator.

package attendance

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	attendance "github.com/xinjiyuan97/labor-clients/biz/model/attendance"
)

// ApplyLeave .
// @router /api/v1/attendance/apply-leave [POST]
func ApplyLeave(ctx context.Context, c *app.RequestContext) {
	var err error
	var req attendance.ApplyLeaveReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(attendance.ApplyLeaveResp)

	c.JSON(consts.StatusOK, resp)
}
