// Code generated by hertz generator.

package attendance

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	attendancelogic "github.com/xinjiyuan97/labor-clients/biz/logic/attendance"
	attendance "github.com/xinjiyuan97/labor-clients/biz/model/attendance"
	"github.com/xinjiyuan97/labor-clients/middleware"
)

// CheckOut .
// @router /api/v1/attendance/checkout [POST]
func CheckOut(ctx context.Context, c *app.RequestContext) {
	var err error
	var req attendance.CheckOutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID, exists := middleware.GetUserIDFromContext(c)
	if !exists {
		c.String(consts.StatusUnauthorized, "未登录")
		return
	}

	resp, err := attendancelogic.CheckOutLogic(ctx, int64(userID), &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
