// Code generated by hertz generator.

package attendance

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	attendance "github.com/xinjiyuan97/labor-clients/biz/model/attendance"
)

// GetAttendanceRecords .
// @router /api/v1/attendance/records [GET]
func GetAttendanceRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req attendance.GetAttendanceRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(attendance.GetAttendanceRecordsResp)

	c.JSON(consts.StatusOK, resp)
}
