// Code generated by hertz generator.

package system

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	systemlogic "github.com/xinjiyuan97/labor-clients/biz/logic/system"
	system "github.com/xinjiyuan97/labor-clients/biz/model/system"
)

// GetNoticeDetail .
// @router /api/v1/system/notices/:notice_id [GET]
func GetNoticeDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.GetNoticeDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := systemlogic.GetNoticeDetailLogic(&req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
