// Code generated by hertz generator.

package system

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	system "github.com/xinjiyuan97/labor-clients/biz/model/system"
)

// SubmitFeedback .
// @router /api/v1/system/feedback [POST]
func SubmitFeedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.SubmitFeedbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system.SubmitFeedbackResp)

	c.JSON(consts.StatusOK, resp)
}
