// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	attendance "github.com/xinjiyuan97/labor-clients/biz/router/attendance"
	auth "github.com/xinjiyuan97/labor-clients/biz/router/auth"
	common "github.com/xinjiyuan97/labor-clients/biz/router/common"
	community "github.com/xinjiyuan97/labor-clients/biz/router/community"
	job "github.com/xinjiyuan97/labor-clients/biz/router/job"
	job_application "github.com/xinjiyuan97/labor-clients/biz/router/job_application"
	message "github.com/xinjiyuan97/labor-clients/biz/router/message"
	payment "github.com/xinjiyuan97/labor-clients/biz/router/payment"
	review "github.com/xinjiyuan97/labor-clients/biz/router/review"
	schedule "github.com/xinjiyuan97/labor-clients/biz/router/schedule"
	system "github.com/xinjiyuan97/labor-clients/biz/router/system"
	upload "github.com/xinjiyuan97/labor-clients/biz/router/upload"
	user "github.com/xinjiyuan97/labor-clients/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	upload.Register(r)

	system.Register(r)

	payment.Register(r)

	review.Register(r)

	attendance.Register(r)

	community.Register(r)

	user.Register(r)

	message.Register(r)

	job_application.Register(r)

	job.Register(r)

	schedule.Register(r)

	auth.Register(r)

	common.Register(r)
}
