// Code generated by hertz generator.

package attendance

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _attendanceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyleaveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applymakeupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getattendancerecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getattendancedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}
